package polldsl.sandbox;

/*Generated by MPS */

import java.io.IOException;
import java.io.FileWriter;

public class map_Test {
  public static void main(String[] args) throws IOException {
    final String top = "<html><head><link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'></head><title>" + "Test" + "</title><body><h1 class='text-center'>" + "Test" + "</h1><div class='container'>";
    String questions = "";
    questions = questions + "<p class='list-group-item'> <b>" + "Pytanie Otwarte" + "</b> <input type='text' name='" + "pytanie1" + "'> </p>";
    {
      questions = questions + "<div class='list-group-item radio'> <b>" + "Pytanie Jednokrotnego Wyboru" + "</b><div class='radio'>";
      String answers = "";
      String nazwa_pytania = "pytanie2";
      answers = answers + "<label class='radio'><input type='radio' name='" + "OdpA" + "' value='" + "Odpowiedz 1" + "'>" + "Odpowiedz 1" + "</label>";
      answers = answers + "<label class='radio'><input type='radio' name='" + "OdpB" + "' value='" + "Odpowiedz 2" + "'>" + "Odpowiedz 2" + "</label>";
      answers = answers + "<label class='radio'><input type='radio' name='" + "odpC" + "' value='" + "Odpowiedz 3" + "'>" + "Odpowiedz 3" + "</label>";
      answers = answers + "<label class='radio'><input type='radio' name='" + "odpD" + "' value='" + "Odpowiedz 4" + "'>" + "Odpowiedz 4" + "</label>";
      questions = questions + answers + "</div></div>";
    }
    {
      questions = questions + "<div class='list-group-item'> <b>" + "PytanieWielokrotnegoWyboru" + "</b><div class='checkbox'>";
      String answers = "";
      String nazwa_pytania = "pytanie3";
      answers = answers + "<label class='checkbox'><input type='checkbox' name='" + "OdpA" + "'value='" + "Odpowiedz 1" + "'>" + "Odpowiedz 1" + "</label>";
      answers = answers + "<label class='checkbox'><input type='checkbox' name='" + "OdpB" + "'value='" + "Odpowiedz 2" + "'>" + "Odpowiedz 2" + "</label>";
      answers = answers + "<label class='checkbox'><input type='checkbox' name='" + "OdpC" + "'value='" + "Odpowiedz 3" + "'>" + "Odpowiedz 3" + "</label>";
      answers = answers + "<label class='checkbox'><input type='checkbox' name='" + "OdpD" + "'value='" + "Odpowiedz 4" + "'>" + "Odpowiedz 4" + "</label>";
      questions = questions + answers + "</div></div>";
    }
    final String bot = "<button type='submit' class='list-group-item'>Wyslij</button></div></body></html>";
    final String result = top + questions + bot;
    String path = System.getProperty("user.home");
    System.out.println("Html file is saved to " + path);
    try (FileWriter writer = new FileWriter(path + "/index.html")) {
      writer.append(result);
    }
  }
}
